import { MAX_FILE_SIZE } from "../types/core";
import { UploadError } from "../utils/errors";
import {
  assertByteSize,
  assertContentType,
  assertWriteMode,
} from "../utils/storage-validation";

import type {
  DeleteOptions,
  DownloadOptions,
  FileInfo,
  UploadOptions,
} from "../types/core";
import { BaseStorageProvider } from "./base";

/**
 * Vercel Blob storage configuration
 *
 * Notes:
 * - If you deploy on the same Vercel project as the Blob store, you usually
 *   *don’t* need to pass a token explicitly – the SDK will use
 *   process.env.BLOB_READ_WRITE_TOKEN automatically.
 * - When running outside Vercel or against a different project, pass a
 *   read-write token via `token`.
 */
export interface VercelBlobConfig {
  /**
   * Read-write token for the Blob store.
   * If omitted on Vercel, @vercel/blob falls back to process.env.BLOB_READ_WRITE_TOKEN.
   */
  token?: string;

  /**
   * Optional logical prefix inside the Blob store.
   * All blob pathnames will be nested under this prefix.
   * Example: "uploads" → "uploads/123-file.png"
   */
  pathPrefix?: string;

  /**
   * Access level for new blobs.
   *
   * Currently Vercel Blob only supports "public" access in the SDK options
   * (the docs treat `access: 'public'` as required).
   */
  access?: "public";

  /**
   * Whether to add a random suffix to the pathname.
   * If not set, we default to `!preserveKey`:
   *   - when preserveKey=false → addRandomSuffix=true (avoid collisions)
   *   - when preserveKey=true  → addRandomSuffix=false (deterministic)
   */
  addRandomSuffix?: boolean;

  /**
   * Default Cache-Control max-age (in seconds) for blobs.
   * See Vercel Blob caching docs.
   */
  cacheControlMaxAge?: number;

  /**
   * Use automatic multipart uploads for large files.
   *
   * When `true`, we pass `multipart: true` to `put()`, which lets Vercel
   * handle splitting and parallelizing the upload under the hood.
   */
  multipart?: boolean;
}

/**
 * Vercel Blob storage provider
 *
 * Uses the official @vercel/blob SDK:
 * - Uploads via `put()`
 * - Deletes via `del()`
 * - Downloads by resolving metadata with `head()` and then fetching the blob URL
 */
export class VercelBlobStorageProvider extends BaseStorageProvider {
  private readonly config: VercelBlobConfig;

  constructor(config: VercelBlobConfig = {}) {
    super();
    this.config = config;
  }

  /**
   * Normalize keys under an optional pathPrefix.
   *
   * - Strips leading slashes from the given key
   * - Strips leading/trailing slashes from pathPrefix
   * - Joins them with a single `/`
   */
  private getFullPath(key: string): string {
    const cleanedKey = this.normalizeKey(key);
    if (!this.config.pathPrefix) {
      return cleanedKey;
    }

    const prefix = this.normalizeKey(
      this.config.pathPrefix.replace(/^\/+|\/+$/g, ""),
    );
    if (cleanedKey === prefix || cleanedKey.startsWith(`${prefix}/`)) {
      return cleanedKey;
    }
    return this.normalizeKey(`${prefix}/${cleanedKey}`);
  }

  /**
   * Upload a file to Vercel Blob using the `put()` SDK method.
   *
   * Docs: `put(pathname, body, options)`
   */
  override async upload(options: UploadOptions): Promise<FileInfo> {
    assertWriteMode(options.writeMode);
    assertContentType(options.contentType);
    if (options.writeMode === "create-only")
      throw new UploadError(
        "PROVIDER_UNSUPPORTED",
        "This provider does not support create-only writes",
      );
    const { file, fileName, contentType, preserveKey, customKey } = options;

    // Sanitize the filename to avoid weird characters
    const safeName = this.sanitizeFilename(fileName);

    // Use customKey if provided; otherwise base key generated by BaseStorageProvider
    const baseKey = customKey || this.generateKey(safeName, preserveKey);
    const pathname = this.getFullPath(baseKey);

    const { put } = await import("@vercel/blob");
    const blob = await put(pathname, file, {
      // Access is required; Vercel currently uses "public"
      access: this.config.access ?? "public",
      // Default: random suffix unless the caller explicitly wants deterministic keys
      addRandomSuffix:
        this.config.addRandomSuffix ?? (preserveKey ? false : true),
      contentType,
      cacheControlMaxAge: this.config.cacheControlMaxAge,
      multipart: this.config.multipart,
      token: this.config.token,
    });

    // The SDK returns url + downloadUrl; we prefer downloadUrl when present
    const path = blob.downloadUrl || blob.url;

    return {
      path,
      key: blob.pathname, // the canonical key inside the store
      name: fileName,
      size: file.length,
      type: blob.contentType || contentType,
    };
  }

  /**
   * Download a blob into memory as a Buffer.
   *
   * There is no `get()` in the SDK; we:
   *  1. Resolve metadata with `head()` (by pathname)
   *  2. Fetch the blob URL over HTTP (stream → ArrayBuffer → Buffer)
   *
   * Docs show `head("filepath", { token })` to retrieve metadata.
   */
  override async download(options: DownloadOptions): Promise<Buffer> {
    if (options.range)
      throw new UploadError(
        "PROVIDER_UNSUPPORTED",
        "This provider does not support range reads",
      );
    if (options.maxBytes !== undefined)
      assertByteSize(options.maxBytes, "Download limit");
    const fullPath = this.getFullPath(options.key);

    // Step 1: resolve the blob metadata to get its URL
    const { head } = await import("@vercel/blob");
    const blobMeta = await head(fullPath, {
      token: this.config.token,
    });

    const url = blobMeta.downloadUrl || blobMeta.url;
    if (!url) {
      throw new Error(
        `Unable to resolve download URL for blob: ${options.key}`,
      );
    }

    if (
      options.maxBytes !== undefined &&
      typeof blobMeta.size === "number" &&
      blobMeta.size > options.maxBytes
    ) {
      throw new Error("File exceeds the configured download limit");
    }

    // Stop reading before an untrusted blob can exhaust the process heap.
    const response = await fetch(url, { signal: AbortSignal.timeout(30_000) });
    if (!response.ok || !response.body)
      throw new UploadError(
        "DOWNLOAD_FAILED",
        "Could not download blob",
        undefined,
        502,
      );
    const limit = options.maxBytes ?? MAX_FILE_SIZE;
    const reader = response.body.getReader();
    const chunks: Buffer[] = [];
    let size = 0;
    try {
      while (true) {
        const chunk = await reader.read();
        if (chunk.done) break;
        size += chunk.value.byteLength;
        if (size > limit)
          throw new UploadError(
            "FILE_TOO_LARGE",
            "File exceeds the configured download limit",
            undefined,
            413,
          );
        chunks.push(Buffer.from(chunk.value));
      }
      return Buffer.concat(chunks, size);
    } finally {
      await reader.cancel().catch(() => undefined);
      reader.releaseLock();
    }
  }

  /**
   * Delete a blob.
   *
   * The SDK’s `del()` accepts either a pathname or a URL and requires a
   * read-write token (via env or `token` option).
   */
  override async delete(options: DeleteOptions): Promise<void> {
    const fullPath = this.getFullPath(options.key);

    const { del } = await import("@vercel/blob");
    await del(fullPath, {
      token: this.config.token,
    });
  }

  /**
   * Vercel Blob doesn’t use classic presigned URLs for uploads/downloads.
   * Instead, it uses token-based client uploads via `@vercel/blob/client`
   * and `handleUpload()` server routes.
   *
   * At this abstraction level, we stick to server-side uploads and don’t
   * expose presigned URLs.
   */
  override supportsPresignedUrls(): boolean {
    return false;
  }

  /**
   * Multipart uploads are handled transparently by `put()` when
   * `multipart: true` is passed in options. We *don’t* provide a manual,
   * S3-style multipart API here.
   */
  override supportsMultipartUpload(): boolean {
    return false;
  }
}
