import { del, head, put } from "@vercel/blob";
import { BaseStorageProvider } from "./base";
import type {
  DeleteOptions,
  DownloadOptions,
  FileInfo,
  UploadOptions,
} from "../types/core";

/**
 * Vercel Blob storage configuration
 *
 * Notes:
 * - If you deploy on the same Vercel project as the Blob store, you usually
 *   *don’t* need to pass a token explicitly – the SDK will use
 *   process.env.BLOB_READ_WRITE_TOKEN automatically. 
 * - When running outside Vercel or against a different project, pass a
 *   read-write token via `token`.
 */
export interface VercelBlobConfig {
  /**
   * Read-write token for the Blob store.
   * If omitted on Vercel, @vercel/blob falls back to process.env.BLOB_READ_WRITE_TOKEN.
   */
  token?: string;

  /**
   * Optional logical prefix inside the Blob store.
   * All blob pathnames will be nested under this prefix.
   * Example: "uploads" → "uploads/123-file.png"
   */
  pathPrefix?: string;

  /**
   * Access level for new blobs.
   *
   * Currently Vercel Blob only supports "public" access in the SDK options
   * (the docs treat `access: 'public'` as required). 
   */
  access?: "public";

  /**
   * Whether to add a random suffix to the pathname.
   * If not set, we default to `!preserveKey`:
   *   - when preserveKey=false → addRandomSuffix=true (avoid collisions)
   *   - when preserveKey=true  → addRandomSuffix=false (deterministic)
   */
  addRandomSuffix?: boolean;

  /**
   * Default Cache-Control max-age (in seconds) for blobs.
   * See Vercel Blob caching docs. 
   */
  cacheControlMaxAge?: number;

  /**
   * Use automatic multipart uploads for large files.
   *
   * When `true`, we pass `multipart: true` to `put()`, which lets Vercel
   * handle splitting and parallelizing the upload under the hood. 
   */
  multipart?: boolean;
}

/**
 * Vercel Blob storage provider
 *
 * Uses the official @vercel/blob SDK:
 * - Uploads via `put()`
 * - Deletes via `del()`
 * - Downloads by resolving metadata with `head()` and then fetching the blob URL
 */
export class VercelBlobStorageProvider extends BaseStorageProvider {
  private readonly config: VercelBlobConfig;

  constructor(config: VercelBlobConfig = {}) {
    super();
    this.config = config;
  }

  /**
   * Normalize keys under an optional pathPrefix.
   *
   * - Strips leading slashes from the given key
   * - Strips leading/trailing slashes from pathPrefix
   * - Joins them with a single `/`
   */
  private getFullPath(key: string): string {
    const cleanedKey = key.replace(/^\/+/, "");
    if (!this.config.pathPrefix) {
      return cleanedKey;
    }

    const prefix = this.config.pathPrefix.replace(/^\/+|\/+$/g, "");
    return `${prefix}/${cleanedKey}`;
  }

  /**
   * Upload a file to Vercel Blob using the `put()` SDK method.
   *
   * Docs: `put(pathname, body, options)` 
   */
  async upload(options: UploadOptions): Promise<FileInfo> {
    const { file, fileName, contentType, preserveKey, customKey } = options;

    // Sanitize the filename to avoid weird characters
    const safeName = this.sanitizeFilename(fileName);

    // Use customKey if provided; otherwise base key generated by BaseStorageProvider
    const baseKey = customKey || this.generateKey(safeName, preserveKey);
    const pathname = this.getFullPath(baseKey);

    const blob = await put(pathname, file, {
      // Access is required; Vercel currently uses "public"
      access: this.config.access ?? "public",
      // Default: random suffix unless the caller explicitly wants deterministic keys
      addRandomSuffix:
        this.config.addRandomSuffix ?? (preserveKey ? false : true),
      contentType,
      cacheControlMaxAge: this.config.cacheControlMaxAge,
      multipart: this.config.multipart,
      token: this.config.token,
    });

    // The SDK returns url + downloadUrl; we prefer downloadUrl when present 
    const path = blob.downloadUrl || blob.url;

    return {
      path,
      key: blob.pathname, // the canonical key inside the store
      name: fileName,
      size: file.length,
      type: blob.contentType || contentType,
    };
  }

  /**
   * Download a blob into memory as a Buffer.
   *
   * There is no `get()` in the SDK; we:
   *  1. Resolve metadata with `head()` (by pathname)
   *  2. Fetch the blob URL over HTTP (stream → ArrayBuffer → Buffer)
   *
   * Docs show `head("filepath", { token })` to retrieve metadata. 
   */
  async download(options: DownloadOptions): Promise<Buffer> {
    const fullPath = this.getFullPath(options.key);

    // Step 1: resolve the blob metadata to get its URL
    const blobMeta = await head(fullPath, {
      token: this.config.token,
    });

    const url = blobMeta.downloadUrl || blobMeta.url;
    if (!url) {
      throw new Error(`Unable to resolve download URL for blob: ${options.key}`);
    }

    // Step 2: stream the blob into memory using global fetch
    const fetchImpl: any = (globalThis as any).fetch;
    if (typeof fetchImpl !== "function") {
      throw new Error(
        "globalThis.fetch is not available in this runtime; cannot download from Vercel Blob."
      );
    }

    const res: any = await fetchImpl(url);
    if (!res.ok) {
      throw new Error(
        `Failed to download blob ${options.key}: ${res.status} ${res.statusText}`
      );
    }

    const arrayBuffer: ArrayBuffer = await res.arrayBuffer();
    return Buffer.from(arrayBuffer);
  }

  /**
   * Delete a blob.
   *
   * The SDK’s `del()` accepts either a pathname or a URL and requires a
   * read-write token (via env or `token` option). 
   */
  async delete(options: DeleteOptions): Promise<void> {
    const fullPath = this.getFullPath(options.key);

    await del(fullPath, {
      token: this.config.token,
    });
  }

  /**
   * Vercel Blob doesn’t use classic presigned URLs for uploads/downloads.
   * Instead, it uses token-based client uploads via `@vercel/blob/client`
   * and `handleUpload()` server routes. 
   *
   * At this abstraction level, we stick to server-side uploads and don’t
   * expose presigned URLs.
   */
  supportsPresignedUrls(): boolean {
    return false;
  }

  /**
   * Multipart uploads are handled transparently by `put()` when
   * `multipart: true` is passed in options. We *don’t* provide a manual,
   * S3-style multipart API here.
   */
  supportsMultipartUpload(): boolean {
    return false;
  }
}
